name: MinigamesCreator
version: '${project.version}'
main: com.special70.minigamescreator.MinigamesCreator
api-version: 1.17
authors: [ Special70 ]
description: Allows you to create your own custom minigames without too much effort
commands:
  die:
    description: An easy way to commit die.
    usage: /<command>
  printMsg:
    description: Grabs the string you typed in config
    usage: /<command>
  micro:
    description: Main command
    usage: /<command>